site_name: RapidForge
site_description: A lightweight Luau utility library for Roblox
site_url: https://StudlyCase.github.io/RapidForge
repo_url: https://github.com/StudlyCase/RapidForge
repo_name: RapidForge

docs_dir: docs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - GUI: GUI.md
  - Animation: ANIMATION.md
  - Player: PLAYER.md
  - World: WORLD.md
  - Math: MATH.md
  - Utility: UTILITY.md
  - Events: EVENTS.md
  - Logger: LOGGER.md
  - Audio: AUDIO.md
  - Services: SERVICE.md
  - Architecture: ../meta/architecture.md
  - Changelog: ../meta/changelog.md
